### ISSUE TITLE
pip install must run as administrator in windows

### ISSUE THREAD

**Issue by vsuh** [jsickcodes/pre-commit-docx-plain#14]

**Comment by vsuh** [comment]
1. pip install must run as administrator in windows (or should use virtualenv?)
2. error in %USERPROFILE%\.cache\pre-commit\pre-commit.log

### version information

```
pre-commit version: 2.13.0
sys.version:
    3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
sys.executable: c:\program files\python38\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found
```

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "c:\program files\python38\lib\site-packages\pre_commit\main.py", line 357, in main
    return hook_impl(
  File "c:\program files\python38\lib\site-packages\pre_commit\commands\hook_impl.py", line 221, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "c:\program files\python38\lib\site-packages\pre_commit\commands\hook_impl.py", line 42, in _run_legacy
    cmd = normalize_cmd((legacy_hook, *args))
  File "c:\program files\python38\lib\site-packages\pre_commit\parse_shebang.py", line 82, in normalize_cmd
    exe = normexe(cmd[0])
  File "c:\program files\python38\lib\site-packages\pre_commit\parse_shebang.py", line 61, in normexe
    _error('not found')
  File "c:\program files\python38\lib\site-packages\pre_commit\parse_shebang.py", line 51, in _error
    raise ExecutableNotFoundError(f'Executable `{orig}` {msg}')
pre_commit.parse_shebang.ExecutableNotFoundError: Executable `/bin/sh` not found
```
